// <auto-generated />
namespace ManagementTool.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FKTeamID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKTeamID));
        
        string IMigrationMetadata.Id
        {
            get { return "201304011453596_FKTeamID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
