// <auto-generated />
namespace ManagementTool.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class datetimeandkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimeandkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201304022042407_datetimeandkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
