// <auto-generated />
namespace ManagementTool.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TableIDRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableIDRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201304011451316_TableIDRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
